# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: common/contact.proto, common/message_data.proto, common/message_element.proto, common/request.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List, Optional

import betterproto


class Scene(betterproto.Enum):
    UNSPECIFIED = 0
    GROUP = 1
    FRIEND = 2
    GUILD = 3
    STRANGER_FROM_GROUP = 11
    NEARBY = 6
    """以下类型为可选实现"""

    STRANGER = 10


class Role(betterproto.Enum):
    UNKNOWN = 0
    MEMBER = 1
    ADMIN = 2
    OWNER = 3


class ElementElementType(betterproto.Enum):
    UNSPECIFIED = 0
    TEXT = 1
    AT = 2
    FACE = 3
    BUBBLE_FACE = 4
    REPLY = 5
    IMAGE = 6
    VOICE = 7
    VIDEO = 8
    BASKETBALL = 9
    DICE = 10
    RPS = 11
    POKE = 12
    MUSIC = 13
    WEATHER = 14
    LOCATION = 15
    SHARE = 16
    GIFT = 17
    MARKET_FACE = 18
    FORWARD = 19
    CONTACT = 20
    JSON = 21
    XML = 22
    FILE = 23
    MARKDOWN = 24
    KEYBOARD = 25


class ImageElementImageType(betterproto.Enum):
    UNSPECIFIED = 0
    COMMON = 1
    ORIGIN = 2
    FLASH = 3


class MusicElementMusicPlatform(betterproto.Enum):
    UNSPECIFIED = 0
    QQ = 1
    NETEASE = 2
    CUSTOM = 11


class ResponseResponseCode(betterproto.Enum):
    UNSPECIFIED = 0
    SUCCESS = 1
    INVALID_ARGUMENT = 2
    INTERNAL = 3
    UNAUTHENTICATED = 4
    PERMISSION_DENIED = 5


@dataclass(eq=False, repr=False)
class Contact(betterproto.Message):
    scene: "Scene" = betterproto.enum_field(1)
    peer: str = betterproto.string_field(2)
    sub_peer: Optional[str] = betterproto.string_field(3, optional=True)


@dataclass(eq=False, repr=False)
class PrivateSender(betterproto.Message):
    uid: Optional[str] = betterproto.string_field(1, optional=True)
    uin: int = betterproto.uint64_field(2)
    nick: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class GroupSender(betterproto.Message):
    group_id: str = betterproto.string_field(1)
    uid: Optional[str] = betterproto.string_field(2, optional=True)
    uin: int = betterproto.uint64_field(3)
    nick: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class GuildSender(betterproto.Message):
    guild_id: str = betterproto.string_field(1)
    channel_id: str = betterproto.string_field(2)
    tiny_id: str = betterproto.string_field(3)
    nick: str = betterproto.string_field(4)
    role: "Role" = betterproto.enum_field(5)


@dataclass(eq=False, repr=False)
class Element(betterproto.Message):
    type: "ElementElementType" = betterproto.enum_field(1)
    """be friendly to some languages that don't support oneof"""

    text: "TextElement" = betterproto.message_field(2, group="data")
    at: "AtElement" = betterproto.message_field(3, group="data")
    face: "FaceElement" = betterproto.message_field(4, group="data")
    bubble_face: "BubbleFaceElement" = betterproto.message_field(5, group="data")
    reply: "ReplyElement" = betterproto.message_field(6, group="data")
    image: "ImageElement" = betterproto.message_field(7, group="data")
    voice: "VoiceElement" = betterproto.message_field(8, group="data")
    video: "VideoElement" = betterproto.message_field(9, group="data")
    basketball: "BasketballElement" = betterproto.message_field(10, group="data")
    dice: "DiceElement" = betterproto.message_field(11, group="data")
    rps: "RpsElement" = betterproto.message_field(12, group="data")
    poke: "PokeElement" = betterproto.message_field(13, group="data")
    music: "MusicElement" = betterproto.message_field(14, group="data")
    weather: "WeatherElement" = betterproto.message_field(15, group="data")
    location: "LocationElement" = betterproto.message_field(16, group="data")
    share: "ShareElement" = betterproto.message_field(17, group="data")
    gift: "GiftElement" = betterproto.message_field(18, group="data")
    market_face: "MarketFaceElement" = betterproto.message_field(19, group="data")
    forward: "ForwardElement" = betterproto.message_field(20, group="data")
    contact: "ContactElement" = betterproto.message_field(21, group="data")
    json: "JsonElement" = betterproto.message_field(22, group="data")
    xml: "XmlElement" = betterproto.message_field(23, group="data")
    file: "FileElement" = betterproto.message_field(24, group="data")
    markdown: "MarkdownElement" = betterproto.message_field(25, group="data")
    keyboard: "KeyboardElement" = betterproto.message_field(26, group="data")


@dataclass(eq=False, repr=False)
class TextElement(betterproto.Message):
    text: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class AtElement(betterproto.Message):
    uid: Optional[str] = betterproto.string_field(1, optional=True)
    uin: Optional[int] = betterproto.uint64_field(2, optional=True)


@dataclass(eq=False, repr=False)
class FaceElement(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    is_big: Optional[bool] = betterproto.bool_field(2, optional=True)
    result: Optional[int] = betterproto.uint32_field(3, optional=True)


@dataclass(eq=False, repr=False)
class BubbleFaceElement(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    count: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class ReplyElement(betterproto.Message):
    message_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ImageElement(betterproto.Message):
    file: bytes = betterproto.bytes_field(1, group="data")
    file_name: str = betterproto.string_field(2, group="data")
    file_path: str = betterproto.string_field(3, group="data")
    file_url: str = betterproto.string_field(4, group="data")
    file_md5: Optional[str] = betterproto.string_field(5, optional=True)
    sub_type: Optional[int] = betterproto.uint32_field(6, optional=True)
    file_type: Optional["ImageElementImageType"] = betterproto.enum_field(10, optional=True)


@dataclass(eq=False, repr=False)
class VoiceElement(betterproto.Message):
    file: bytes = betterproto.bytes_field(1, group="data")
    file_name: str = betterproto.string_field(2, group="data")
    file_path: str = betterproto.string_field(3, group="data")
    file_url: str = betterproto.string_field(4, group="data")
    file_md5: Optional[str] = betterproto.string_field(5, optional=True)
    magic: Optional[bool] = betterproto.bool_field(6, optional=True)


@dataclass(eq=False, repr=False)
class VideoElement(betterproto.Message):
    file: bytes = betterproto.bytes_field(1, group="data")
    file_name: str = betterproto.string_field(2, group="data")
    file_path: str = betterproto.string_field(3, group="data")
    file_url: str = betterproto.string_field(4, group="data")
    file_md5: Optional[str] = betterproto.string_field(5, optional=True)


@dataclass(eq=False, repr=False)
class BasketballElement(betterproto.Message):
    id: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class DiceElement(betterproto.Message):
    id: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class RpsElement(betterproto.Message):
    id: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class PokeElement(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    poke_type: int = betterproto.uint32_field(2)
    strength: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class CustomMusicData(betterproto.Message):
    url: str = betterproto.string_field(1)
    audio: str = betterproto.string_field(2)
    title: str = betterproto.string_field(3)
    author: str = betterproto.string_field(4)
    pic: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class MusicElement(betterproto.Message):
    platform: "MusicElementMusicPlatform" = betterproto.enum_field(1)
    id: str = betterproto.string_field(2, group="data")
    custom: "CustomMusicData" = betterproto.message_field(3, group="data")


@dataclass(eq=False, repr=False)
class WeatherElement(betterproto.Message):
    city: str = betterproto.string_field(1)
    code: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class LocationElement(betterproto.Message):
    lat: float = betterproto.float_field(1)
    lon: float = betterproto.float_field(2)
    title: str = betterproto.string_field(3)
    address: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class ShareElement(betterproto.Message):
    url: str = betterproto.string_field(1)
    title: str = betterproto.string_field(2)
    content: str = betterproto.string_field(3)
    image: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class GiftElement(betterproto.Message):
    qq: int = betterproto.uint64_field(1)
    id: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class MarketFaceElement(betterproto.Message):
    id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ForwardElement(betterproto.Message):
    res_id: str = betterproto.string_field(1)
    uniseq: str = betterproto.string_field(2)
    summary: str = betterproto.string_field(3)
    description: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class ContactElement(betterproto.Message):
    scene: "Scene" = betterproto.enum_field(1)
    peer: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class JsonElement(betterproto.Message):
    json: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class XmlElement(betterproto.Message):
    xml: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class FileElement(betterproto.Message):
    name: Optional[str] = betterproto.string_field(1, optional=True)
    size: Optional[int] = betterproto.uint64_field(2, optional=True)
    expire_time: Optional[int] = betterproto.uint64_field(3, optional=True)
    id: Optional[str] = betterproto.string_field(4, optional=True)
    url: Optional[str] = betterproto.string_field(5, optional=True)
    biz: Optional[int] = betterproto.int32_field(6, optional=True)
    sub_id: Optional[str] = betterproto.string_field(7, optional=True)


@dataclass(eq=False, repr=False)
class MarkdownElement(betterproto.Message):
    markdown: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ButtonActionPermission(betterproto.Message):
    type: int = betterproto.int32_field(1)
    role_ids: List[str] = betterproto.string_field(2)
    user_ids: List[str] = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ButtonAction(betterproto.Message):
    type: int = betterproto.int32_field(1)
    permission: "ButtonActionPermission" = betterproto.message_field(2)
    unsupported_tips: str = betterproto.string_field(3)
    data: str = betterproto.string_field(4)
    reply: bool = betterproto.bool_field(5)
    enter: bool = betterproto.bool_field(6)


@dataclass(eq=False, repr=False)
class ButtonRender(betterproto.Message):
    label: str = betterproto.string_field(1)
    visited_label: str = betterproto.string_field(2)
    style: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class Button(betterproto.Message):
    id: str = betterproto.string_field(1)
    render_data: "ButtonRender" = betterproto.message_field(2)
    action: "ButtonAction" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class KeyboardRow(betterproto.Message):
    buttons: List["Button"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class KeyboardElement(betterproto.Message):
    rows: List["KeyboardRow"] = betterproto.message_field(1)
    bot_appid: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class PushMessageBody(betterproto.Message):
    time: int = betterproto.uint64_field(1)
    message_id: str = betterproto.string_field(2)
    """
    消息 id
     长度 |           1           |        20         |    20    |
     内容 | 群聊为 'g' 私聊为 'p' | 群 uin 或好友 uin | 消息 Seq |
    """

    message_seq: int = betterproto.uint64_field(3)
    scene: "Scene" = betterproto.enum_field(4)
    private: "PrivateSender" = betterproto.message_field(5, group="sender")
    group: "GroupSender" = betterproto.message_field(6, group="sender")
    guild: "GuildSender" = betterproto.message_field(7, group="sender")
    elements: List["Element"] = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class ForwardMessageBody(betterproto.Message):
    message_id: str = betterproto.string_field(1, group="forward_message")
    message: "PushMessageBody" = betterproto.message_field(2, group="forward_message")


@dataclass(eq=False, repr=False)
class EssenceMessageBody(betterproto.Message):
    group_id: int = betterproto.uint32_field(1)
    sender_uid: Optional[str] = betterproto.string_field(2, optional=True)
    sender_uin: int = betterproto.uint64_field(3)
    sender_nick: str = betterproto.string_field(4)
    operator_uid: Optional[int] = betterproto.uint64_field(5, optional=True)
    operator_uin: int = betterproto.uint64_field(6)
    operator_nick: str = betterproto.string_field(7)
    operation_time: int = betterproto.uint64_field(8)
    message_time: int = betterproto.uint64_field(9)
    message_id: str = betterproto.string_field(10)
    message_seq: int = betterproto.uint64_field(11)
    json_elements: str = betterproto.string_field(12)


@dataclass(eq=False, repr=False)
class Request(betterproto.Message):
    cmd: str = betterproto.string_field(1)
    seq: int = betterproto.uint32_field(2)
    buf: bytes = betterproto.bytes_field(3)
    no_response: bool = betterproto.bool_field(4)


@dataclass(eq=False, repr=False)
class Response(betterproto.Message):
    cmd: str = betterproto.string_field(1)
    seq: int = betterproto.uint32_field(2)
    code: "ResponseResponseCode" = betterproto.enum_field(3)
    msg: Optional[str] = betterproto.string_field(4, optional=True)
    buf: bytes = betterproto.bytes_field(5)
